slam_toolbox:
  ros__parameters:
    use_sim_time: true
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    mode: mapping
    map_update_interval: 1.5
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.8
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    throttle_scans: 2

    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.10
    minimum_travel_heading: 0.10

    loop_search_maximum_distance: 6.0
    loop_match_minimum_chain_size: 8
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
    do_loop_closing: true
